/**
 * Hyperledger API
 * Hyperledger API reference for developers
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@oferto.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Trade { 
    creationDate?: string;
    id?: string;
    owner?: string;
    price?: number;
    tradeType?: string;
    updatedDate?: string;
    value?: number;
}

